version: '2'

# volumes:
#   molecular-design-applications-gitcache:
#     external: true
#   molecular-design-applications-storage:
#     external: true

services:

  server:
    build:
      context: .
    command: ["nodemon", "--watch", "/app/build", "/app/build/server/server-workflow.js"]
    ports:
      - "4000:4000"
    environment:
      HOST_PWD: "${PWD}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${PWD}/tmp:/app/tmp"
      - "${PWD}/gitcache:/app/gitcache"
      # Uncomment this if you are doing server development
      # - ./build/server:/app/build/server
      # - ./build/web:/app/build/web
      - ./node_modules:/app/node_modules
      - ./build:/app/build
      - ./test:/app/test
